import { clipboard } from "electron";
import { createHash } from "node:crypto";
import { historyStore } from "../history/historyStore";
import { settingsStore } from "../settings/settingsStore";
import { looksLikeTechnicalNoise } from "../../shared/format/looksLikeTechnicalNoise";
import { logger } from "../logger";

const POLL_INTERVAL_MS = 900;

/**
 * Pasteboard/format markers a well-behaved clipboard manager is expected to
 * honor. Password managers (1Password, Bitwarden, Dashlane, ...) and macOS's
 * own passkey/password autofill declare one of these alongside sensitive
 * content specifically so tools like Potli skip it — this is the standard
 * "org.nspasteboard" convention on macOS, plus KeePass's older Windows
 * convention. We check for these on every poll before touching the content.
 */
const CONCEALED_FORMAT_MARKERS = [
  "org.nspasteboard.ConcealedType",
  "org.nspasteboard.TransientType",
  "org.nspasteboard.AutoGeneratedType",
  "Clipboard Viewer Ignore"
];

let timer: ReturnType<typeof setInterval> | null = null;
let lastSignature: string | null = null;
/** Signature of the last write Potli itself made to the clipboard — used to
 * skip re-adding Potli's own capture/re-copy writes as a second, redundant
 * "clipboard" history entry (see clipboardService.ts). */
let suppressSignature: string | null = null;

function signatureFor(kind: "text" | "image", data: string | Buffer): string {
  return createHash("sha1").update(kind).update(data).digest("hex");
}

/** Called by clipboardService right after Potli writes to the clipboard itself. */
export function noteProgrammaticWrite(kind: "text" | "image", data: string | Buffer): void {
  suppressSignature = signatureFor(kind, data);
}

function isConcealed(): boolean {
  try {
    return clipboard.availableFormats().some((f) => CONCEALED_FORMAT_MARKERS.includes(f));
  } catch {
    return false;
  }
}

/** Runs one clipboard check. Exported (not just used by the interval) so tests
 * can call it directly without depending on real timers. */
export async function checkClipboardOnce(): Promise<void> {
  if (!settingsStore.get("clipboardWatcherEnabled")) return;
  if (isConcealed()) return;

  try {
    const image = clipboard.readImage();
    if (!image.isEmpty()) {
      const png = image.toPNG();
      const sig = signatureFor("image", png);
      if (sig === lastSignature) return;
      lastSignature = sig;
      if (sig === suppressSignature) {
        suppressSignature = null;
        return;
      }
      const size = image.getSize();
      if (size.width < 1 || size.height < 1) return;
      await historyStore.addImage({
        region: { width: size.width, height: size.height },
        imageBuffer: png,
        origin: "clipboard"
      });
      return;
    }

    const text = clipboard.readText();
    if (text && text.trim()) {
      const sig = signatureFor("text", text);
      if (sig === lastSignature) return;
      lastSignature = sig;
      if (sig === suppressSignature) {
        suppressSignature = null;
        return;
      }
      if (looksLikeTechnicalNoise(text)) return;
      await historyStore.addText({
        text,
        rawText: text,
        engine: "clipboard",
        language: "",
        origin: "clipboard"
      });
      return;
    }

    // Nothing on the clipboard (or an unsupported format) — reset so a later
    // matching copy is still detected as new rather than treated as a repeat.
    lastSignature = null;
  } catch (error) {
    logger.warn("Clipboard watcher poll failed", { error: String(error) });
  }
}

export function startClipboardWatcher(): void {
  if (timer) return;
  timer = setInterval(() => {
    void checkClipboardOnce();
  }, POLL_INTERVAL_MS);
}

export function stopClipboardWatcher(): void {
  if (timer) {
    clearInterval(timer);
    timer = null;
  }
}
